### ISSUE TITLE
Načítavanie energie pri selected políčku

### ISSUE THREAD

**Issue by Parado2X** [LeoSight/leosight-eco#1]
**Popiš chybu**
Chyba spôsobuje to, že pokiaľ máte nedostatok energie napríklad na obsadenie poľa a pole máte vybrané (pravé tlačítko) tak pole nemôžete obsadiť (logicky), no pokiaľ sa vám energia načíta, a máte dostatočný počet energie na to aby ste pole mohli obsadiť, tlačítko bude šedé a nebude sa dať naň kliknúť. Aby ste zase pole mohli obsadiť, musíte si na pole prekliknúť.

**Reprodukce**
Kliknete pravým tlačítkom na akékoľvek pole ktoré dokážete dobyť
Dostaňte sa pod hodnotu obsadenia pola (ak pole vyžaduje 2 energie, tak musíte mať pod 2)
Potom už len čakajte kým hodnota dosiahne číslo ktoré si obsadenie pola vyžaduje

**Očekávané chování**
Tlačítko by sa malo aktualizovať spolu s vašou energiou a na tlačítko by sa po načítaní energie malo dať kliknúť

**Comment by RatajVaver** [comment]
Určitě je to důležitá připomínka a tuto věc by chtělo ve hře lépe vyřešit (jak popisuješ již popisuješ očekávané chování). Zatím jsem nepřišel na to, jak udělat jakýsi reload disabled podmínky u [jQuery contextMenu](https://swisnl.github.io/jQuery-contextMenu/), který by se pak jen snadno napojil k eventu při kterém hráč obdrží nové počty energie a surovin.

Pokud chce někdo pomoct s řešením tohoto Issue, můžete zjistit a ozkoušet, jak by se dalo existující řešení kontextového menu aktualizovat bez uzavření a otevření (očividně se také refreshne při kliknutí na libovolné tlačítko - viz. přepínač na disabled v dokumentaci). Případně by nebylo špatné zvážit úplně jiné řešení pro kontextové menu, které nám nabídne více možností (můžeme také vytvořit vlastní).
