### ISSUE TITLE
Maximální počet surovin

### ISSUE THREAD

**Issue by Arci224** [LeoSight/leosight-eco#15]
**Popiš chybu**
Při vylepšení skladu se nezaktualizuje maximální počet surovin v pravo nahoře v té tabulce.

**Reprodukce**
Vylepšit sklad.

**Očekávané chování**
Aktualizovat se maximální hodnota surovin.

**Comment by RatajVaver** [comment]
Opravu již mám připravenou, bude v dalším updatu.
