### ISSUE TITLE
"Boti"

### ISSUE THREAD

**Issue by Arci224** [LeoSight/leosight-eco#4]
**Popiš chybu**
Chyba způsobuje to že se dá uměle navíšit počet lidí na serveru.

**Reprodukce**
Ve své podstatě se to normálně hráči nestane, ale pokuď si hráč otevře v prohlížeči vývojářské prostředí a poté otevře consoli a tam zadá například
`
io().on('pong', function(ms) {
	console.log(ms)
})
`
Tak mu to vytvoří novou instanci čímž tedy způsobí navíšení hráčů na serveru uměle.

**Očekávané chování**
No určitě by to asi nemělo připočítat dalšího hráče.

**Comment by Arci224** [comment]
Po trochu bližším zkoušení jsem kdyžtak přišel na to že stačí pouze `io()` zadat do console. S tím že tedy dokuď si uživatel neobnoví stránku tak to tedy bere jakožto nového hráče poté. (Snad je to k pochopení kdyžtak DM me na discu.)

**Comment by RatajVaver** [comment]
Ano, pravděpodobně by server mohl povolit jen určitý počet instancí na IP adresu, případně také počítat do online hráčů pouze ty již přihlášené. Přidávám do TODO.
